### ISSUE TITLE
Never get the links

### ISSUE THREAD

**Issue by rsoorajs** [FayasNoushad/Pixeldrain-Bot#4]
Showing `Uploaded successfully` in telegram and never get the links. heroku logs are provided below

```
2021-12-07T09:27:47.917809+00:00 heroku[worker.1]: State changed from starting to up
2021-12-07T09:27:51.595921+00:00 app[worker.1]: Pyrogram v1.2.12, Copyright (C) 2017-2021 Dan <https://github.com/delivrance>
2021-12-07T09:27:51.595938+00:00 app[worker.1]: Licensed under the terms of the GNU Lesser General Public License v3 or later (LGPLv3+)
2021-12-07T09:27:51.595938+00:00 app[worker.1]: 
2021-12-07T09:28:24.764102+00:00 app[worker.1]: argument of type 'TypeError' is not iterable
2021-12-07T09:28:24.764109+00:00 app[worker.1]: Traceback (most recent call last):
2021-12-07T09:28:24.764110+00:00 app[worker.1]:   File "/app/main.py", line 62, in media_filter
2021-12-07T09:28:24.764110+00:00 app[worker.1]:     if response["success"] is False:
2021-12-07T09:28:24.764111+00:00 app[worker.1]: TypeError: 'Response' object is not subscriptable
2021-12-07T09:28:24.764112+00:00 app[worker.1]: 
2021-12-07T09:28:24.764113+00:00 app[worker.1]: During handling of the above exception, another exception occurred:
2021-12-07T09:28:24.764113+00:00 app[worker.1]: 
2021-12-07T09:28:24.764113+00:00 app[worker.1]: Traceback (most recent call last):
2021-12-07T09:28:24.764114+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/pyrogram/dispatcher.py", line 217, in handler_worker
2021-12-07T09:28:24.764114+00:00 app[worker.1]:     await handler.callback(self.client, *args)
2021-12-07T09:28:24.764115+00:00 app[worker.1]:   File "/app/main.py", line 69, in media_filter
2021-12-07T09:28:24.764115+00:00 app[worker.1]:     if "MESSAGE_NOT_MODIFIED" in error:
2021-12-07T09:28:24.764115+00:00 app[worker.1]: TypeError: argument of type 'TypeError' is not iterable
```

**Comment by rsoorajs** [comment]
tried with different files types and getting same error

**Comment by rsoorajs** [comment]
@FayasNoushad

**Comment by FayasNoushad** [comment]
Deploy branch again
