### ISSUE TITLE
Issue Still persists 

### ISSUE THREAD

**Issue by rsoorajs** [FayasNoushad/Pixeldrain-Bot#6]
Issue still persists .Just showing "uploaded successfully" in telegram and no links generating
https://github.com/FayasNoushad/Pixeldrain-Bot/issues/5

Heroku logs

```
2021-12-07T11:49:10.024877+00:00 app[worker.1]: Pyrogram v1.2.12, Copyright (C) 2017-2021 Dan <https://github.com/delivrance>
2021-12-07T11:49:10.025452+00:00 app[worker.1]: Licensed under the terms of the GNU Lesser General Public License v3 or later (LGPLv3+)
2021-12-07T11:49:10.025454+00:00 app[worker.1]: 
2021-12-07T11:49:46.738931+00:00 app[worker.1]: 'Response' object is not subscriptable
2021-12-07T11:49:46.738941+00:00 app[worker.1]: Traceback (most recent call last):
2021-12-07T11:49:46.738943+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/pyrogram/dispatcher.py", line 217, in handler_worker
2021-12-07T11:49:46.738943+00:00 app[worker.1]:     await handler.callback(self.client, *args)
2021-12-07T11:49:46.738944+00:00 app[worker.1]:   File "/app/main.py", line 85, in media_filter
2021-12-07T11:49:46.738945+00:00 app[worker.1]:     text = f"**File Name:** `{data['name']}`" + "\n"
2021-12-07T11:49:46.738945+00:00 app[worker.1]: TypeError: 'Response' object is not subscriptable
```

**Comment by FayasNoushad** [comment]
Fixed
